= Préparation du projet Qualite_TP1 avec Maven

:author: Votre Nom
:date: 29 septembre 2023
:toc:

== Introduction

Ce README explique les étapes nécessaires pour préparer le projet Java "Qualite_TP1" en utilisant Maven. Le processus comprend la commande "clean" pour nettoyer les fichiers temporaires, la commande "compile" pour compiler le code source, la commande "package" pour créer un fichier JAR exécutable, et enfin, la génération de la documentation Javadoc pour le projet.

== Prérequis

Avant de commencer, assurez-vous d'avoir les éléments suivants installés sur votre système :

1. [Java JDK](https://www.oracle.com/java/technologies/javase-downloads.html) - Java Development Kit (version 8 ou supérieure).
2. [Apache Maven](https://maven.apache.org/download.cgi) - Outil de gestion de projet Java.

== Instructions

Pour préparer le projet "Qualite_TP1" avec Maven, suivez ces étapes :

=== Étape 1: Clonage du projet

Clonez le projet depuis son référentiel Git en utilisant la commande suivante :

[source,shell]
----
git clone <URL_DU_REPO>
----

Remplacez `<URL_DU_REPO>` par l'URL du référentiel Git de votre projet.

=== Étape 2: Accéder au répertoire du projet

Accédez au répertoire du projet en utilisant la commande suivante :

[source,shell]
----
cd Qualite_TP1
----

=== Étape 3: Nettoyage du projet

Pour nettoyer les fichiers temporaires et les artefacts de build précédents, exécutez la commande "clean" de Maven :

[source,shell]
----
mvn clean
----

=== Étape 4: Compilation

Compilez le code source Java en utilisant la commande "compile" de Maven :

[source,shell]
----
mvn compile
----

=== Étape 5: Package JAR

Créez un fichier JAR exécutable en utilisant la commande "package" de Maven. Le fichier JAR sera généralement créé dans le répertoire "target" du projet.

[source,shell]
----
mvn package
----

=== Étape 6: Génération de la documentation Javadoc

Générez la documentation Javadoc pour le projet en utilisant la commande suivante :

[source,shell]
----
mvn javadoc:javadoc
----

La documentation Javadoc sera générée dans le répertoire "target/site/apidocs".

== Conclusion

Votre projet Java "Qualite_TP1" est maintenant prêt à être exécuté avec le fichier JAR généré et vous disposez également de la documentation Javadoc pour référence. N'hésitez pas à personnaliser ce README en fonction de votre projet spécifique et de ses besoins.

Pour plus d'informations sur l'utilisation de Maven, consultez la [documentation officielle de Maven](https://maven.apache.org/guides/index.html).
